import React, {useState} from "react";
import Head from "next/head";
import styles from "./game.module.sass";
import { Card } from "@/components/Card";

const Game = () => {
  const [stageNum, setStageNum] = useState(0);
  const stageInfo = [
    "只有點擊出牌翻牌部份的程式拆解，其他的請靠自己囉",
    "click and start",
    "Shuffling",
    "pick up the 1st card",
    "pick up the 2nd card",
    "pick up the 3rd card",
    "click and restart"
  ];

  const mainClick = () => {

  }

  return (
    <>
      <Head>
        <title>塔羅翻牌 react 組件版</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.game}>
        <div className={styles.tip}>
          {stageInfo[stageNum]}
        </div>
        <Card
          posiName="card1"
          cardNum="5"
        />
      </main>
    </>
  );
};
export default Game;


function waittings(time){
  return new Promise(resolve => {
    setTimeout(()=>{
      resolve();
    }, time);
  });
}